[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
evm_version = "shanghai"

[fuzz]
runs = 10_000

[fmt]
line_length = 100
bracket_spacing = true
multiline_func_header = "params_first"
ignore = ["src/util/Sauce.sol"]
